// <auto-generated />
using System;
using Escalonadores.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Escalonadores.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Escalonadores.Model.Escalonador", b =>
                {
                    b.Property<long>("idEscalonador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_escalonador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idEscalonador"));

                    b.Property<string>("nomeEscalonador")
                        .HasColumnType("text")
                        .HasColumnName("nome_escalonador");

                    b.HasKey("idEscalonador");

                    b.ToTable("escalonador");

                    b.HasData(
                        new
                        {
                            idEscalonador = 1L,
                            nomeEscalonador = "Round Robin"
                        },
                        new
                        {
                            idEscalonador = 2L,
                            nomeEscalonador = "Shortest Job First"
                        },
                        new
                        {
                            idEscalonador = 3L,
                            nomeEscalonador = "Shortest Remaining Time First"
                        },
                        new
                        {
                            idEscalonador = 4L,
                            nomeEscalonador = "Prioridade Não-Preemptivo"
                        });
                });

            modelBuilder.Entity("Escalonadores.Model.EscalonadorExecucao", b =>
                {
                    b.Property<long>("idEscalonadorExecucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_escalonador_execucao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idEscalonadorExecucao"));

                    b.Property<long>("contador_medico")
                        .HasColumnType("bigint")
                        .HasColumnName("contador_medico");

                    b.Property<long>("fim")
                        .HasColumnType("bigint")
                        .HasColumnName("fim");

                    b.Property<long>("idExecucao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_execucao");

                    b.Property<long>("idPaciente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_paciente");

                    b.Property<long>("inicio")
                        .HasColumnType("bigint")
                        .HasColumnName("inicio");

                    b.HasKey("idEscalonadorExecucao");

                    b.ToTable("escalonador_execucao");
                });

            modelBuilder.Entity("Escalonadores.Model.Execucao", b =>
                {
                    b.Property<long>("idExecucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_execucao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idExecucao"));

                    b.Property<DateTime>("dataExecucao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_execucao");

                    b.Property<long>("idAlgoritmo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_algoritmo");

                    b.Property<double>("mediaCPU")
                        .HasColumnType("double precision")
                        .HasColumnName("media_cpu");

                    b.Property<double>("mediaEspera")
                        .HasColumnType("double precision")
                        .HasColumnName("media_espera");

                    b.Property<double>("mediaExecucao")
                        .HasColumnType("double precision")
                        .HasColumnName("media_execucao");

                    b.Property<long>("nMedicos")
                        .HasColumnType("bigint")
                        .HasColumnName("n_medicos");

                    b.Property<long>("nTrocasContexto")
                        .HasColumnType("bigint")
                        .HasColumnName("n_trocas_contexto");

                    b.HasKey("idExecucao");

                    b.ToTable("execucao");
                });

            modelBuilder.Entity("Escalonadores.Model.Paciente", b =>
                {
                    b.Property<long>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idPaciente"));

                    b.Property<long>("duracao")
                        .HasColumnType("bigint")
                        .HasColumnName("duracao");

                    b.Property<long>("idExecucao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_execucao");

                    b.Property<long>("idPrioridadeManchester")
                        .HasColumnType("bigint")
                        .HasColumnName("id_prioridade_manchester");

                    b.Property<long?>("quantum")
                        .HasColumnType("bigint")
                        .HasColumnName("quantum");

                    b.Property<long>("tempoChegada")
                        .HasColumnType("bigint")
                        .HasColumnName("tempo_chegada");

                    b.Property<long>("tempoSaida")
                        .HasColumnType("bigint")
                        .HasColumnName("tempo_saida");

                    b.HasKey("idPaciente");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("Escalonadores.Model.PrioridadeManchester", b =>
                {
                    b.Property<long>("idPrioridadeManchester")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_prioridade_manchester");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idPrioridadeManchester"));

                    b.Property<string>("cor")
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<string>("nomePrioridade")
                        .HasColumnType("text")
                        .HasColumnName("nome_prioridade");

                    b.HasKey("idPrioridadeManchester");

                    b.ToTable("prioridade_manchester");

                    b.HasData(
                        new
                        {
                            idPrioridadeManchester = 1L,
                            cor = "Vermelho",
                            nomePrioridade = "Emergência"
                        },
                        new
                        {
                            idPrioridadeManchester = 2L,
                            cor = "Laranja",
                            nomePrioridade = "Muito Urgente"
                        },
                        new
                        {
                            idPrioridadeManchester = 3L,
                            cor = "Amarelo",
                            nomePrioridade = "Urgente"
                        },
                        new
                        {
                            idPrioridadeManchester = 4L,
                            cor = "Verde",
                            nomePrioridade = "Pouco Urgente"
                        },
                        new
                        {
                            idPrioridadeManchester = 5L,
                            cor = "Azul",
                            nomePrioridade = "Não Urgente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
